function B = ReadBusLog(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 02-Nov-2011 10:58:08

% Import the file
% Columns are:
%  vehicleID
%  dirTag (includes route and variant
%  reportTime (msec since epoch)
%  dataAge (seconds since this data was reported)
%  lat
%  lon
%  heading
A = importdata(fileToRead1);

B.ID = A.textdata(:,1);
B.dirTag = A.textdata(:,2);
B.time = A.data(:,1)*.001 - A.data(:,2);
B.age = A.data(:,2);
B.lat = A.data(:,3);
B.lon = A.data(:,4);
B.heading = A.data(:,5);

